#!/bin/bash

git checkout target/linux/ramips/mt7621/config-4.4

echo "
CONFIG_WL_MEDIATEK=y
CONFIG_WIFI_DRIVER=y
# CONFIG_FIRST_IF_NONE is not set
# CONFIG_FIRST_IF_MT7615E is not set
# CONFIG_FIRST_IF_MT7603E is not set
# CONFIG_FIRST_IF_MT7663E is not set
# CONFIG_FIRST_IF_MT7622 is not set
# CONFIG_FIRST_IF_MT7626 is not set
CONFIG_FIRST_IF_MT7915=y
# CONFIG_FIRST_IF_MT7986 is not set
CONFIG_SECOND_IF_NONE=y
# CONFIG_SECOND_IF_MT7615E is not set
# CONFIG_SECOND_IF_MT7915 is not set
# CONFIG_SECOND_IF_MT7986 is not set
# CONFIG_SECOND_IF_MT7603E is not set
# CONFIG_SECOND_IF_MT7663E is not set
CONFIG_THIRD_IF_NONE=y
# CONFIG_THIRD_IF_MT7615E is not set
CONFIG_RT_FIRST_CARD=7915
CONFIG_RT_FIRST_IF_RF_OFFSET=0xc0000
# CONFIG_WIFI_MT7603E is not set
# CONFIG_WIFI_MT7663E is not set
CONFIG_WIFI_MT_SINGLE=y
CONFIG_MT_WIFI=y
CONFIG_MT_WIFI_PATH=\"mt_wifi\"

#
# WiFi Generic Feature Options
#
CONFIG_FIRST_IF_EEPROM_FLASH=y
# CONFIG_FIRST_IF_EEPROM_PROM is not set
# CONFIG_FIRST_IF_EEPROM_EFUSE is not set
CONFIG_RT_FIRST_CARD_EEPROM=\"flash\"
CONFIG_WIFI_BASIC_FUNC=y
CONFIG_DOT11_N_SUPPORT=y
CONFIG_DOT11_VHT_AC=y
CONFIG_DOT11_HE_AX=y
CONFIG_CFG_SUPPORT_FALCON_MURU=y
CONFIG_CFG_SUPPORT_FALCON_TXCMD_DBG=y
CONFIG_CFG_SUPPORT_FALCON_SR=y
CONFIG_CFG_SUPPORT_FALCON_PP=y
CONFIG_WIFI_TWT_SUPPORT=y
CONFIG_G_BAND_256QAM_SUPPORT=y
# CONFIG_BRCM_256QAM_SUPPORT is not set
CONFIG_TPC_SUPPORT=y
# CONFIG_THERMAL_PROTECT_SUPPORT is not set
CONFIG_ICAP_SUPPORT=y
CONFIG_SPECTRUM_SUPPORT=y
CONFIG_BACKGROUND_SCAN_SUPPORT=y
CONFIG_SMART_CARRIER_SENSE_SUPPORT=y
CONFIG_SCS_FW_OFFLOAD=y
CONFIG_MT_DFS_SUPPORT=y
CONFIG_DBDC_MODE=y
CONFIG_MULTI_PROFILE_SUPPORT=y
# CONFIG_DEFAULT_5G_PROFILE is not set
CONFIG_OFFCHANNEL_SCAN_FEATURE=y
CONFIG_HDR_TRANS_TX_SUPPORT=y
CONFIG_HDR_TRANS_RX_SUPPORT=y
CONFIG_WSC_INCLUDED=y
CONFIG_WSC_V2_SUPPORT=y
CONFIG_DOT11W_PMF_SUPPORT=y
CONFIG_TXBF_SUPPORT=y
# CONFIG_VHT_TXBF_2G_EPIGRAM_IE_SUPPORT is not set
# CONFIG_WIFI_SYSDVT is not set
CONFIG_WIFI_DBG_TXCMD=y
CONFIG_FAST_NAT_SUPPORT=y
# CONFIG_FTM_SUPPORT is not set
# CONFIG_MBO_SUPPORT is not set
CONFIG_IGMP_SNOOP_SUPPORT=y
CONFIG_RTMP_FLASH_SUPPORT=y
# CONFIG_PRE_CAL_TRX_SET1_SUPPORT is not set
# CONFIG_RLM_CAL_CACHE_SUPPORT is not set
# CONFIG_PRE_CAL_TRX_SET2_SUPPORT is not set
CONFIG_CAL_BIN_FILE_SUPPORT=y
# CONFIG_RF_LOCKDOWN_SUPPORT is not set
# CONFIG_LINK_TEST_SUPPORT is not set
CONFIG_ATE_SUPPORT=y
CONFIG_WLAN_SERVICE=y
CONFIG_PASSPOINT_R2=y
CONFIG_MBO_SUPPORT=y
CONFIG_OCE_SUPPORT=y
CONFIG_MAP_SUPPORT=y
CONFIG_MAP_R2_VER_SUPPORT=y
CONFIG_UAPSD=y
# CONFIG_TCP_RACK_SUPPORT is not set
CONFIG_RED_SUPPORT=y
# CONFIG_FDB_SUPPORT is not set
CONFIG_FIRST_IF_EPAELNA=y
# CONFIG_FIRST_IF_IPAILNA is not set
# CONFIG_FIRST_IF_IPAELNA is not set
# CONFIG_RLT_MAC is not set
# CONFIG_RTMP_MAC is not set

#
# WiFi Operation Modes
#
CONFIG_WIFI_MODE_AP=y
# CONFIG_WIFI_MODE_STA is not set
# CONFIG_WIFI_MODE_BOTH is not set
CONFIG_MT_AP_SUPPORT=y
CONFIG_WDS_SUPPORT=y
# CONFIG_WIFI_EAP_FEATURE is not set
# CONFIG_WIFI_GPIO_CTRL is not set
CONFIG_MBSS_SUPPORT=y
CONFIG_APCLI_SUPPORT=y
CONFIG_APCLI_CERT_SUPPORT=y
CONFIG_MAC_REPEATER_SUPPORT=y
CONFIG_WIFI_SYSTEM_DVT=n
# CONFIG_APCLI_CONNECTION_TRIAL is not set
# CONFIG_MWDS is not set
CONFIG_MUMIMO_SUPPORT=y
CONFIG_MU_RA_SUPPORT=y
CONFIG_DOT11R_FT_SUPPORT=y
CONFIG_DOT11K_RRM_SUPPORT=y
# CONFIG_KVRH_SUPPORT is not set
CONFIG_INTERWORKING=y
# CONFIG_BS_SUPPORT is not set
# CONFIG_WAPP_SUPPORT is not set
# CONFIG_SNIFFER_SUPPORT is not set
# CONFIG_ENTERPRISE_AP_SUPPORT is not set
# CONFIG_ANTENNA_CONTROL_SUPPORT is not set
# CONFIG_WIFI_EAP_FEATURE is not set
# CONFIG_CFG80211_SUPPORT is not set
# CONFIG_MBSS_AS_WDS_AP_SUPPORT is not set
# CONFIG_DSCP_QOS_MAP_SUPPORT is not set
# CONFIG_DSCP_PRI_SUPPORT is not set
# CONFIG_MIN_PHY_RATE_SUPPORT is not set
# CONFIG_FAST_UP_RATE_SUPPORT is not set
CONFIG_CON_WPS_SUPPORT=y
CONFIG_MCAST_RATE_SPECIFIC=y
CONFIG_VOW_SUPPORT=y
CONFIG_BAND_STEERING=y
# CONFIG_LED_CONTROL_SUPPORT is not set
CONFIG_WLAN_HOOK=y
# CONFIG_RADIUS_ACCOUNTING_SUPPORT is not set
CONFIG_GREENAP_SUPPORT=y
# CONFIG_TXRX_STAT_SUPPORT is not set
# CONFIG_VENDOR_FEATURE11_SUPPORT is not set
CONFIG_PCIE_ASPM_DYM_CTRL_SUPPORT=y
# CONFIG_COEX_SUPPORT is not set
# CONFIG_EASY_SETUP_SUPPORT is not set
# CONFIG_EVENT_NOTIFIER_SUPPORT is not set
CONFIG_AIR_MONITOR=y
CONFIG_WNM_SUPPORT=y
# CONFIG_INTERWORKING is not set
# CONFIG_LINUX_NET_TXQ_SUPPORT is not set
CONFIG_WPA3_SUPPORT=y
CONFIG_OWE_SUPPORT=y
CONFIG_VLAN_SUPPORT=y
# CONFIG_RCSA_SUPPORT is not set
CONFIG_CTXD_MEM_CPY_SUPPORT=y
# CONFIG_CTXD_SCATTER_AND_GATHER_SUPPORT is not set
CONFIG_SINGLE_SKU=y
CONFIG_MLME_MULTI_QUEUE_SUPPORT=y
# CONFIG_PROFILING_SUPPORT is not set
CONFIG_WIFI_MT_MAC=y
CONFIG_MT_MAC=y
# CONFIG_CHIP_MT7603E is not set
# CONFIG_CHIP_MT7615E is not set
# CONFIG_CHIP_MT7622 is not set
# CONFIG_CHIP_MT7663E is not set
# CONFIG_CHIP_MT7626 is not set
# CONFIG_CHIP_MT7663U is not set
# CONFIG_CHIP_AXE is not set
CONFIG_CHIP_MT7915=y
CONFIG_WIFI_DIAG=y
CONFIG_CONN_FAIL_EVENT=y
# CONFIG_MEMORY_OPTIMIZATION is not set
" >> target/linux/ramips/mt7621/config-4.4


